### ISSUE TITLE
[2.4.2] Security problem CVE-2012-6708

### ISSUE THREAD

**Issue by sanfrancrisko** [puppetlabs/puppet-lint#9]
Installed version: 1.6.4
Fixed version: 1.9.0
Installation
path / port: /usr/share/gems/doc/puppet-lint-2.4.2/rdoc/js/jquery.js

Originally reported: https://github.com/rodjek/puppet-lint/issues/947

**Comment by bastelfreak** [comment]
@sanfrancrisko can you elaborate this a bit? where is the jquery file coming from, a gem dependency?

**Comment by ekohl** [comment]
These files aren't shipped with the gem itself. This looks like what happens if you install it via a package. You mention port so is that FreeBSD? Should this be picked up with the BSD packagers?

Also, if I now generate docs using `rdoc` I no longer see `jquery.js` so perhaps rdoc moved on?

cc @tuxmaster5000 who originally reported the issue.

**Comment by tuxmaster5000** [comment]
Very interesting. Did you mean that the files was created by an old version of rdoc  at the install process?

**Comment by ekohl** [comment]
I think that's likely.

**Comment by chelnak** [comment]
I think this has since been resolved. Closing but always happy to re-open if we need to.

Also tagging @puppetlabs/security for visibility.
